### ISSUE TITLE
Encapsulated task decorator

### ISSUE THREAD

**Issue by willviles** [machty/ember-concurrency-decorators#15]
Just wondering if there's any planned support (or workaround) for [encapsulated tasks](http://ember-concurrency.com/docs/encapsulated-task)?

The following raises the error: 

```js
import { task } from 'ember-concurrency-decorators'
import { task as inlineTask } from 'ember-concurrency'

class Foo {
  @task({
    drop: true
  })
  fooTask = inlineTask({
    * perform () {
      // Task logic
    }
  })
}
```

`Assertion Failed: ember-concurrency-decorators: Can only decorate a generator function as a task.`

Perhaps the following syntax could work for a new decorator?

```js
import { encapsulatedTask } from 'ember-concurrency-decorators'

class Foo {
  @encapsulatedTask({
    drop: true
  })
  fooTask = {
    * perform () {
      // Task logic
    }
  }
}
```

**Comment by buschtoens** [comment]
We definitely should support [encapsulated tasks](http://ember-concurrency.com/docs/encapsulated-task). Thank you for raising the issue!

In order to reduce the amount of different decorators, ideally all existing [`@task` decorators](https://github.com/machty/ember-concurrency-decorators#task) would also be usable for encapsulated tasks. We can use the different syntactical constructs to differentiate between regular and encapsulated tasks, as you suggested.

```ts
import { dropTask } from 'ember-concurrency-decorators'

class Foo {
  @dropTask
  regularDropTask = function*() {
    ...
  };

  @dropTask
  encapsulatedDropTask = {
    somePrivateState: true,
    *perform() {
      ...
    }
  };
}
```

Implementation should be pretty straightforward. We just change this assertion to allow objects with a `perform` generator method on them as well.

https://github.com/machty/ember-concurrency-decorators/blob/fcd36840a3c07163eff1cf066e398a2630f865f6/addon/index.js#L58-L61

What do you think?

I am also open to alternative API suggestions.

We could potentially add an `@encapsulate` decorator (for lack of a better name) instead like:

```ts
import { dropTask, encapsulate } from 'ember-concurrency-decorators'

class Foo {
  @dropTask
  regularDropTask = function*() {
    ...
  };

  @dropTask
  @encapsulate({
    somePrivateState: true
  })
  encapsulatedDropTask = function*() {
    ...
  };
}
```

The reason being, that this could potentially look nicer with the soon supported [generator method syntax](https://github.com/machty/ember-concurrency-decorators#typescript):


```ts
import { dropTask, encapsulate } from 'ember-concurrency-decorators'

class Foo {
  @dropTask
  *regularDropTask() {
    ...
  }

  @dropTask
  @encapsulate({
    somePrivateState: true
  })
  *encapsulatedDropTask() {
    ...
  }
}
```

**Comment by willviles** [comment]
Wow, super speedy PR! Thanks @buschtoens.

I think it's probably overkill to introduce a secondary decorator. Just supplying an object is definitely the cleanest solution.
