### ISSUE TITLE
TypeScript : "Property 'perform' does not exist..." on Task

### ISSUE THREAD

**Issue by theseyi** [machty/ember-concurrency-decorators#30]
The following causes typescript to raise the type error at the bottom:

```typescript
import Component from '@ember/component';
import { task } from 'ember-concurrency-decorators';

export default class ExampleComponent extends Component {
  @task
  *doStuff() {
  }

  executeTheTask() {
    this.doStuff.perform();
  }
}
```
```
Error:(75, 52) TS2339: Property 'perform' does not exist on type '() => IterableIterator<any>'.
```

**Comment by buschtoens** [comment]
That warning is "correct". Unfortunately decorators still cannot change the type signature of the thing that they decorate. The TypeScript will only further develop decorators support, once the proposal for decorators hit stage 3. But they are aware and have it on their road map.

I have gone through numerous ideas for workarounds in the #e-typescript and they all fall flat on their face in one they or another. Another big problem is that the type definition for generator functions loses some information, as the types of all `yield`ed values and the `return` value are merged.

The "best" solution would require significant syntactical overhead to force-feed TypeScript:

```ts
import Component from '@ember/component';
import { task, Task } from 'ember-concurrency-decorators';

export default class ExampleComponent extends Component {
  @task
  *doStuff() {
  }

  executeTheTask() {
    ((this.doStuff as unknown) as Task).perform();
  }
}
```

The above code assumes `Task` type to be exported by this addon.

**Comment by buschtoens** [comment]
If we assume, that users _only_ `yield` Promises, we can actually infer the return type, because the return value cannot be a `Promise`, since ember-concurrency would await and unwrap it.

If I add the following (unfinished) types:

```ts
export function asTask<Args extends any[], R>(
  task: GeneratorFn<Args, R>
): Task<Args, Exclude<R, Promise<any>>>;

export function asTask<Args extends any[], R>(task: {
  perform: GeneratorFn<Args, R>;
}): Task<Args, Exclude<R, Promise<any>>>;

export interface Task<Args extends any[], R> {
  perform(...args: Args): Promise<R>;
  lastSuccessful?: {
    value: R;
  };
  // ...
}

export interface TaskGroup {
  cancelAll(): void;
  // ...
}

type GeneratorFn<Args extends any[] = any[], R = any> = (
  ...args: Args
) => IterableIterator<R>;
```

The following works:

```ts
import Controller from '@ember/controller';
import { task, taskGroup, TaskGroup, Task, asTask } from 'ember-concurrency-decorators';

export class Foo extends Controller {
  @taskGroup saveTaskGroup!: TaskGroup;

  @task
  *someTask(someArg: number) {
    yield Promise.resolve('foo');
    return false;
  }

  @task
  encapsulated = {
    *perform(someArg: number) {
      yield Promise.resolve('foo');
      return false;
    }
  };

  exec() {
    const foo = asTask(this.someTask).perform(3); // => Promise<false>
    const bar = asTask(this.encapsulated).perform(3); // => Promise<false>

    this.saveTaskGroup.cancelAll();
  }
}
```

**Big but**: if users yield a non-`Promise` value, it would be part of the return type.

```ts
class {
  @task
  *someTask(someArg: number) {
    yield Promise.resolve('foo');
    yield 'bar';
    return false;
  }
  exec() {
    const foo = asTask(this.someTask).perform(3); // => Promise<'bar' | false>
  }
}
```

IMO yielding a something that is not a `Promise` (assuming everything is typed properly here) does not make sense and users would be nudged to remove the incorrect `yield` or fix the type of it.

In worst case scenario, they could still cast the return value without `as unknown` since the return type will be a super set of the actual return type.

**Comment by buschtoens** [comment]
@jamescdavis suggested another great idea on Discord. He wrote types that allow the following:

```ts
class Foo {
  myTask = task(function*(this: Foo) {
    yield Promise.resolve('foo');
    return 'bar';
  });

  exec() {
    this.myTask.perform();
  }
}
```

AFAICT this has a problem though. It should cause https://github.com/machty/ember-concurrency/issues/271.

But if you combine this with the babel transform approach, we could transform all occurrences of `identifier = task(...)` to something that is similar to what the `@task` decorator does and defines the task on the prototype.

The massive advantage of this approach is, that you don't have to wrap your task in `asTask()` whenever you want to access it.

On the long run, when TS finally supports the new decorators spec, we'll probably want to converge on the `@task` decorator solution, since the syntax looks nicer IMO and also would not need any transpilation then.

I think I can easily implement both solutions in parallel. We can also provide codemods to switch between the two and also to strip `asTask()`, when TypeScript lands decorator support.

**Comment by peabnuts123** [comment]
First of all I want to say I commend everybody's effort in making this addon in an attempt to bridge some gaps in the ecosystem right now. But to be honest, this issue makes this addon a bit useless. As it stands, you can only use this addon if you are using ES6 classes with JavaScript. I would say people are mostly adopting native classes because of TypeScript - which this addon essentially doesn't support right now (in no small part due to TypeScript itself). Coupled with the fact that the main addon doesn't work at all using native-classes, this leaves a pretty decent amount of projects that essentially cannot use `ember-concurrency` at-all. Is there some kind of workaround that can be developed to declare the tasks in a different way for the interim? Say, a utility function that takes a generator and returns an instance of Task or something (roughly suggested above), but still requiring the decorator? In the future we could then just remove that function. Or perhaps a type definition that we can explicitly define our Task properties as?  I understand the limitations of inferring types from generators and that's a perfectly legitimate issue to be resolved upstream (FWIW: It's not a safe assumption to assume people will only yield Promises. It's pretty common to just `return` a value from an async function if you don't need to do any async work, as the `async/await` standard is expected to deal with that).

For what it's worth, you can get-by for now by just laundering your types through `any`:
```TypeScript
  init() {
    super.init();
    this.myTask.perform();
  }

  // @NOTE Launder types here by explicitly typing `myTask` as `any`
  @task
  myTask: any = function*() {
    // ...
  };
```

**Comment by buschtoens** [comment]
> First of all I want to say I commend everybody's effort in making this addon in an attempt to bridge some gaps in the ecosystem right now.

Thanks 😊 

> But to be honest, this issue makes this addon a bit useless. As it stands, you can only use this addon if you are using ES6 classes with JavaScript. I would say people are mostly adopting native classes because of TypeScript - which this addon essentially doesn't support right now (in no small part due to TypeScript itself).

I'm totally with you!

> Is there some kind of workaround that can be developed to declare the tasks in a different way for the interim? Say, a utility function that takes a generator and returns an instance of Task or something (roughly suggested above), but still requiring the decorator?

Yes, I do think so! I haven't tested this, but I think this would be the right direction.

```ts
import { timeout } from 'ember-concurrency';
import { task } from 'ember-concurrency-decorators';

type GeneratorFn<Args extends any[] = any[], R = any> = (
  ...args: Args
) => IterableIterator<R>;

function asTask<Args extends any[], R>(
  task: GeneratorFn<Args, R>
): Task<Args, Exclude<R, Promise<any>>> {
  // @ts-ignore
  return task;
}

interface Task<Args extends any[], R> {
  perform(...args: Args): Promise<R>;
  lastSuccessful?: {
    value: R;
  };
  // ...
}

class Foo {
  bar = 1337;

  @task
  myTask = asTask(function*(this: Foo) {
    yield timeout(500);
    return this.bar;
  });
}

**Comment by buschtoens** [comment]
I made a PoC in #50.

**Comment by jamescdavis** [comment]
This is now solved by https://github.com/chancancode/ember-concurrency-ts

https://github.com/chancancode/ember-concurrency-ts#alternate-usage-of-taskfor provides the same functionality as #56
