### ISSUE TITLE
Fails with latest ember-decorators and Ember canary

### ISSUE THREAD

**Issue by simonihmig** [machty/ember-concurrency-decorators#38]
Given
* `ember-concurrency-decorators@0.5.3`
* `ember-decorators@5.1.3`
*  `ember-source@canary` (latest build)

I get a `Uncaught TypeError: Cannot read property 'writable' of undefined` exception. The stack trace shows:
* the TypeError being thrown [here](https://github.com/machty/ember-concurrency-decorators/blob/0febf2ed24d281fd2c0eb1d04a289fbcc38cac99/addon/index.js#L60)
* `computedDecorator` calling `fn` without args [here](https://github.com/ember-decorators/ember-decorators/blob/master/packages/utils/addon/computed.js#L48)
* `fn` being this callback [here](https://github.com/machty/ember-concurrency-decorators/blob/0febf2ed24d281fd2c0eb1d04a289fbcc38cac99/addon/index.js#L126-L131), which expects a descriptor as its argument, which is not there (`undefined`)

This came up after upgrading to the latest ember canary, and then upgrading `ember-decorators` to the latest release to fix some other issue there. So apparently related to https://github.com/ember-decorators/ember-decorators/pull/398, which introduced a different implementation of `computedDecorator` for Ember 3.9.0 (see the implementations separated by `gte('3.9.0')`) .

But I *guess* ember-decorators is not to blame here, as `computedDecorator` is undocumented and seems to be a private API, right?

/cc @buschtoens @pzuraq

**Comment by buschtoens** [comment]
_Technically_ [`@e-d/utils`](https://github.com/ember-decorators/ember-decorators/tree/master/packages/utils/) is public API, but it has undergone breaking changes in with the `5.1.3` release. Yesterday I've chatted with @pzuraq about this in `#e-decorators`.

I tried quick fixing it, but it's not as easy, especially since ember-concurrency itself does not work with Ember 3.9 just yet: https://github.com/machty/ember-concurrency/pull/277

My recommendation so far is: Stick to `5.1.2` for a few more days. I am aware of the problem and affected as well, so I am actively tying to fix it asap, promised. ☺️ 👍 

Also do not upgrade to Ember 3.9 canary yet. If you need to use a canary, because of feature flags, use that latest 3.8 canary. :)

**Comment by simonihmig** [comment]
> so I am actively tying to fix it asap, promised.

Much appreciated! 😍

> Stick to `5.1.2` for a few more days.

Will do so, thanks!

> Also do not upgrade to Ember 3.9 canary yet. If you need to use a canary, because of feature flags, use that latest 3.8 canary. :)

Fwiw, I was using an earlier 3.9 canary build before, which *was* working. But I guess this didn't include the mentioned Descriptor changes yet, so will revert to that build...

**Comment by buschtoens** [comment]
I've published [`v0.5.5`](https://github.com/machty/ember-concurrency-decorators/releases/tag/v0.5.5) which adds support for @ember-decorators `^5.1.4` and the latest Ember beta [`v3.9.0-beta.2`](https://github.com/emberjs/ember.js/releases/tag/v3.9.0-beta.2).

It does however not yet support canary, because ember-concurrency and @ember-decorators itself don't support it yet. So I'll keep this open. ☺️

**Comment by buschtoens** [comment]
Fixed in `ember-concurrency-decorators` [`v0.6.0`](https://github.com/machty/ember-concurrency-decorators/releases/tag/v0.6.0). 🎉
